const LEAD_SCHEMA_NAME = {
  FIRST_NAME: 'FirstName',
  LAST_NAME: 'LastName',
  PROSPECT_STAGE: 'ProspectStage',
  PHOTO_URL: 'PhotoUrl',
  COMPANY: 'Company',
  MOBILE: 'Mobile',
  PHONE: 'Phone',
  EMAIL_ADDRESS: 'EmailAddress',
  MX_STREET1: 'mx_Street1',
  MX_CITY: 'mx_City',
  MX_STATE: 'mx_State',
  MX_COUNTRY: 'mx_Country',
  JOB_TITLE: 'JobTitle',
  OWNER_ID: 'OwnerId',
  OWNER_ID_NAME: 'OwnerIdName',
  LEAD_AGE: 'LeadAge',
  TWITTER_ID: 'TwitterId',
  FACEBOOK_ID: 'FacebookId',
  LINKEDIN_ID: 'LinkedInId',
  SKYPE_ID: 'SkypeId',
  GTALK_ID: 'GTalkId',
  GOOGLE_PLUS_ID: 'GooglePlusId',
  LEAD_QUALITY: 'QualityScore01',
  LEAD_ENGAGEMENT_SCORE: 'EngagementScore',
  IS_STARRED_LEAD: 'IsStarredLead',
  DO_NOT_EMAIL: 'DoNotEmail',
  DO_NOT_CALL: 'DoNotCall',
  DO_NOT_TRACK: 'DoNotTrack',
  RELEATED_COMPANY_ID: 'RelatedCompanyId',
  RELATED_COMPANY_ID_NAME: 'RelatedCompanyIdName',
  IS_PRIMARY_CONTACT: 'IsPrimaryContact',
  ADDRESS: 'Address',
  OWNER: 'Owner',
  COMPANY_NAME: 'CompanyName',
  STAGE: 'Stage',
  CITY: 'City',
  WEBSITE: 'Website',
  OWNER_ID_EMAIL_ADDRESS: 'OwnerIdEmailAddress',
  LEAD_IDENTIFIER: 'LeadIdentifier',
  LeadType: 'LeadType'
};

export { LEAD_SCHEMA_NAME };
