export const OldMenuData = [
  {
    Id: '10',
    ParentId: null,
    Caption: 'Home',
    HelpText: 'Snapshot of your marketing analytics',
    ShowHelptext: true,
    ControllerName: 'Dashboard',
    ActionName: '',
    ImageURL: null,
    RelatedConnectorId: null,
    CustomApplicationMenuId: null,
    Group: 1,
    Children: null,
    Path: 'dashboard',
    SortOrder: 0
  },
  {
    Id: '20',
    ParentId: null,
    Caption: 'Content',
    HelpText: '',
    ShowHelptext: true,
    ControllerName: 'EmailLibrary',
    ActionName: '',
    ImageURL: null,
    RelatedConnectorId: null,
    CustomApplicationMenuId: null,
    Group: 1,
    Children: [
      {
        Id: '21',
        ParentId: '20',
        Caption: 'Email Library',
        HelpText: 'Manage your reusable email content',
        ShowHelptext: true,
        ControllerName: 'EmailLibrary',
        ActionName: '',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 1,
        Children: [],
        Path: 'content>>emaillibrary',
        SortOrder: 100
      },
      {
        Id: '22',
        ParentId: '20',
        Caption: 'Images & Documents',
        HelpText: 'Manage your images and documents',
        ShowHelptext: true,
        ControllerName: 'FileBrowser',
        ActionName: '',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 1,
        Children: [],
        Path: 'content>>images&documents',
        SortOrder: 200
      }
    ],
    Path: 'content',
    SortOrder: 0
  },
  {
    Id: '30',
    ParentId: null,
    Caption: 'Marketing',
    HelpText: '',
    ShowHelptext: true,
    ControllerName: 'Campaign',
    ActionName: '',
    ImageURL: null,
    RelatedConnectorId: null,
    CustomApplicationMenuId: null,
    Group: 1,
    Children: [
      {
        Id: '31',
        ParentId: '30',
        Caption: 'Email Campaigns',
        HelpText: 'Send email campaigns and analyze results',
        ShowHelptext: true,
        ControllerName: 'Campaign',
        ActionName: '',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 1,
        Children: [],
        Path: 'marketing>>emailcampaigns',
        SortOrder: 200
      },
      {
        Id: '33',
        ParentId: '30',
        Caption: 'Landing Pages',
        HelpText: 'Manage landing pages and analyze lead conversion',
        ShowHelptext: true,
        ControllerName: 'LandingPages',
        ActionName: '',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 1,
        Children: [],
        Path: 'marketing>>landingpages',
        SortOrder: 400
      },
      {
        Id: '34',
        ParentId: '30',
        Caption: 'Website Widgets',
        HelpText: 'Increase your website visitor to lead conversion',
        ShowHelptext: true,
        ControllerName: 'Widgets',
        ActionName: 'Index',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 5,
        Children: [],
        Path: 'marketing>>websitewidgets',
        SortOrder: 500
      }
    ],
    Path: 'marketing',
    SortOrder: 0
  },
  {
    Id: '40',
    ParentId: null,
    Caption: 'Leads',
    HelpText: '',
    ShowHelptext: true,
    ControllerName: 'LeadManagement',
    ActionName: '',
    ImageURL: null,
    RelatedConnectorId: null,
    CustomApplicationMenuId: null,
    Group: 1,
    Children: [
      {
        Id: '46',
        ParentId: '40',
        Caption: 'Smart Views',
        HelpText: 'Organize and manage your leads and activities using Smart Views',
        ShowHelptext: true,
        ControllerName: 'LeadManagement',
        ActionName: 'SmartViews',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 5,
        Children: [],
        Path: 'leads>>smartviews',
        SortOrder: 200
      },
      {
        Id: '12000',
        ParentId: '40',
        Caption: 'Manage Accounts',
        HelpText: null,
        ShowHelptext: false,
        ControllerName: 'AccountManagement',
        ActionName: '',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 0,
        Children: [
          {
            Id: '12001',
            ParentId: '12000',
            Caption: 'Customers',
            HelpText: null,
            ShowHelptext: false,
            ControllerName: 'AccountManagement',
            ActionName: 'Customers',
            ImageURL: null,
            RelatedConnectorId: null,
            CustomApplicationMenuId: null,
            Group: 0,
            Children: [],
            Path: 'leads>>manageaccounts>>customers',
            SortOrder: null
          },
          {
            Id: '12002',
            ParentId: '12000',
            Caption: 'Dealers',
            HelpText: null,
            ShowHelptext: false,
            ControllerName: 'AccountManagement',
            ActionName: 'Dealers',
            ImageURL: null,
            RelatedConnectorId: null,
            CustomApplicationMenuId: null,
            Group: 0,
            Children: [],
            Path: 'leads>>manageaccounts>>dealers',
            SortOrder: null
          },
          {
            Id: '12003',
            ParentId: '12000',
            Caption: 'Partners',
            HelpText: null,
            ShowHelptext: false,
            ControllerName: 'AccountManagement',
            ActionName: 'Partners',
            ImageURL: null,
            RelatedConnectorId: null,
            CustomApplicationMenuId: null,
            Group: 0,
            Children: [],
            Path: 'leads>>manageaccounts>>partners',
            SortOrder: null
          }
        ],
        Path: 'leads>>manageaccounts',
        SortOrder: 299
      },
      {
        Id: '42',
        ParentId: '40',
        Caption: 'Manage Leads',
        HelpText: 'Manage leads and notable activities',
        ShowHelptext: true,
        ControllerName: 'LeadManagement',
        ActionName: '',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 1,
        Children: [],
        Path: 'leads>>manageleads',
        SortOrder: 300
      },
      {
        Id: '13000',
        ParentId: '40',
        Caption: 'Manage ',
        HelpText: null,
        ShowHelptext: false,
        ControllerName: 'OpportunityManagement?ec=',
        ActionName: '',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 0,
        Children: [
          {
            Id: '13001',
            ParentId: '13000',
            Caption: 'Hemanth_ActRetrSearchParam_1. Ver_1725970772s',
            HelpText: null,
            ShowHelptext: false,
            ControllerName: 'OpportunityManagement?ec=12002',
            ActionName: '',
            ImageURL: null,
            RelatedConnectorId: null,
            CustomApplicationMenuId: null,
            Group: 0,
            Children: [],
            Path: 'leads>>manage>>hemanth_actretrsearchparam_1.ver_1725970772s',
            SortOrder: null
          },
          {
            Id: '13002',
            ParentId: '13000',
            Caption: 'Hemanth_ActRetrSearchParam_1. Ver_1725971219s',
            HelpText: null,
            ShowHelptext: false,
            ControllerName: 'OpportunityManagement?ec=12003',
            ActionName: '',
            ImageURL: null,
            RelatedConnectorId: null,
            CustomApplicationMenuId: null,
            Group: 0,
            Children: [],
            Path: 'leads>>manage>>hemanth_actretrsearchparam_1.ver_1725971219s',
            SortOrder: null
          },
          {
            Id: '13003',
            ParentId: '13000',
            Caption: 'Hemanth_ActRetrSearchParam_2. Ver_1725968311s',
            HelpText: null,
            ShowHelptext: false,
            ControllerName: 'OpportunityManagement?ec=12001',
            ActionName: '',
            ImageURL: null,
            RelatedConnectorId: null,
            CustomApplicationMenuId: null,
            Group: 0,
            Children: [],
            Path: 'leads>>manage>>hemanth_actretrsearchparam_2.ver_1725968311s',
            SortOrder: null
          },
          {
            Id: '13004',
            ParentId: '13000',
            Caption: 'Opportunities',
            HelpText: null,
            ShowHelptext: false,
            ControllerName: 'OpportunityManagement?ec=12000',
            ActionName: '',
            ImageURL: null,
            RelatedConnectorId: null,
            CustomApplicationMenuId: null,
            Group: 0,
            Children: [],
            Path: 'leads>>manage>>opportunities',
            SortOrder: null
          }
        ],
        Path: 'leads>>manage',
        SortOrder: 301
      },
      {
        Id: '45',
        ParentId: '40',
        Caption: 'Manage Activities',
        HelpText: 'Manage and view notable activities',
        ShowHelptext: true,
        ControllerName: 'ActivityManagement',
        ActionName: '',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 1,
        Children: [],
        Path: 'leads>>manageactivities',
        SortOrder: 400
      },
      {
        Id: '43',
        ParentId: '40',
        Caption: 'Manage Tasks',
        HelpText: 'Manage and view tasks',
        ShowHelptext: true,
        ControllerName: 'Tasks',
        ActionName: 'AllTasks',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 1,
        Children: [],
        Path: 'leads>>managetasks',
        SortOrder: 500
      },
      {
        Id: '44',
        ParentId: '40',
        Caption: 'Manage Lists',
        HelpText: 'Organize your leads by creating static and dynamic lists',
        ShowHelptext: true,
        ControllerName: 'ManageLists',
        ActionName: '',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 1,
        Children: [],
        Path: 'leads>>managelists',
        SortOrder: 600
      }
    ],
    Path: 'leads',
    SortOrder: 0
  },
  {
    Id: '50',
    ParentId: null,
    Caption: 'Workflow',
    HelpText: '',
    ShowHelptext: true,
    ControllerName: '',
    ActionName: '',
    ImageURL: null,
    RelatedConnectorId: null,
    CustomApplicationMenuId: null,
    Group: 1,
    Children: [
      {
        Id: '51',
        ParentId: '50',
        Caption: 'Automation',
        HelpText: 'Create visual workflows',
        ShowHelptext: true,
        ControllerName: 'Automation',
        ActionName: 'Index',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 5,
        Children: [],
        Path: 'workflow>>automation',
        SortOrder: 100
      },
      {
        Id: '523',
        ParentId: '50',
        Caption: 'Manage Forms',
        HelpText: '',
        ShowHelptext: true,
        ControllerName: 'Form',
        ActionName: 'Index',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 5,
        Children: [],
        Path: 'workflow>>manageforms',
        SortOrder: 200
      },
      {
        Id: '524',
        ParentId: '50',
        Caption: 'Process Designer',
        HelpText: '',
        ShowHelptext: true,
        ControllerName: 'ProcessDesigner',
        ActionName: 'Index',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 5,
        Children: [],
        Path: 'workflow>>processdesigner',
        SortOrder: 300
      },
      {
        Id: '525',
        ParentId: '50',
        Caption: 'Manage Portals',
        HelpText: 'Manage Portals',
        ShowHelptext: true,
        ControllerName: 'Portal',
        ActionName: 'Index',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 5,
        Children: [],
        Path: 'workflow>>manageportals',
        SortOrder: 400
      }
    ],
    Path: 'workflow',
    SortOrder: 0
  },
  {
    Id: '60',
    ParentId: null,
    Caption: 'Apps',
    HelpText: '',
    ShowHelptext: true,
    ControllerName: 'Apps',
    ActionName: 'MarketPlace',
    ImageURL: null,
    RelatedConnectorId: null,
    CustomApplicationMenuId: null,
    Group: 1,
    Children: [
      {
        Id: '530',
        ParentId: '60',
        Caption: 'Mobile Home Builder',
        HelpText: 'Manage Mobile Home - Builder',
        ShowHelptext: true,
        ControllerName: 'a',
        ActionName: 'HomeBuilder',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 5,
        Children: [],
        Path: 'apps>>mobilehomebuilder',
        SortOrder: 0
      },
      {
        Id: '61',
        ParentId: '60',
        Caption: 'Apps Marketplace',
        HelpText: 'Get additional apps for your LeadSquared account',
        ShowHelptext: true,
        ControllerName: 'Apps',
        ActionName: 'Marketplace',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 1,
        Children: [],
        Path: 'apps>>appsmarketplace',
        SortOrder: 200
      },
      {
        Id: '50000',
        ParentId: '60',
        Caption: 'WhatsApp Templates',
        HelpText: 'Custom',
        ShowHelptext: true,
        ControllerName: 'CustomApplication',
        ActionName: 'Index',
        ImageURL: null,
        RelatedConnectorId: 'f5157de8-aa33-11e9-ae16-0258598489d8',
        CustomApplicationMenuId: 'gg606c9d-7172-3132-c329-c08c308f6b37',
        Group: 5,
        Children: [],
        Path: 'apps>>whatsapptemplates',
        SortOrder: null
      },
      {
        Id: '50001',
        ParentId: '60',
        Caption: 'WhatsApp Reports',
        HelpText: 'Custom',
        ShowHelptext: true,
        ControllerName: 'CustomApplication',
        ActionName: 'Index',
        ImageURL: null,
        RelatedConnectorId: 'f5157de8-aa33-11e9-ae16-0258598489d8',
        CustomApplicationMenuId: 'd2417ad5-ca55-4c38-9362-d8d82526f266',
        Group: 5,
        Children: [],
        Path: 'apps>>whatsappreports',
        SortOrder: null
      },
      {
        Id: '50003',
        ParentId: '60',
        Caption: 'Nudges Connector',
        HelpText: '',
        ShowHelptext: true,
        ControllerName: 'CustomApplication',
        ActionName: 'Index',
        ImageURL: null,
        RelatedConnectorId: '48ffc7ba-df4c-11ed-ab02-02f2f38344f3',
        CustomApplicationMenuId: 'add5fb36-4bd6-11ea-b77f-2e728ce88125',
        Group: 5,
        Children: [],
        Path: 'apps>>nudgesconnector',
        SortOrder: null
      }
    ],
    Path: 'apps',
    SortOrder: 0
  },
  {
    Id: '70',
    ParentId: null,
    Caption: 'Reports',
    HelpText: '',
    ShowHelptext: true,
    ControllerName: 'Reports',
    ActionName: null,
    ImageURL: null,
    RelatedConnectorId: null,
    CustomApplicationMenuId: null,
    Group: 1,
    Children: [
      {
        Id: '71',
        ParentId: '70',
        Caption: 'Reports Home',
        HelpText: 'View reports and analytics',
        ShowHelptext: true,
        ControllerName: 'Reports',
        ActionName: 'List',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 1,
        Children: [],
        Path: 'reports>>reportshome',
        SortOrder: 100
      },
      {
        Id: '72',
        ParentId: '70',
        Caption: 'My Favourite Reports',
        HelpText: 'View your favourite reports',
        ShowHelptext: true,
        ControllerName: 'Reports',
        ActionName: 'Favourites',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 1,
        Children: [],
        Path: 'reports>>myfavouritereports',
        SortOrder: 200
      },
      {
        Id: '73',
        ParentId: '70',
        Caption: 'My Saved Reports',
        HelpText: 'View your saved reports',
        ShowHelptext: true,
        ControllerName: 'Reports',
        ActionName: 'BookMarks',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 1,
        Children: [],
        Path: 'reports>>mysavedreports',
        SortOrder: 300
      }
    ],
    Path: 'reports',
    SortOrder: 0
  },
  {
    Id: '300',
    ParentId: null,
    Caption: 'Settings',
    HelpText: '',
    ShowHelptext: true,
    ControllerName: 'Settings/MyProfile',
    ActionName: '',
    ImageURL: '/Content/LeadSquared/Common/img/user_option_settings.png',
    RelatedConnectorId: null,
    CustomApplicationMenuId: null,
    Group: 2,
    Children: [],
    Path: 'settings',
    SortOrder: 1
  },
  {
    Id: '302',
    ParentId: null,
    Caption: 'Sign Out',
    HelpText: '',
    ShowHelptext: true,
    ControllerName: 'Home',
    ActionName: 'SignOut',
    ImageURL: '/Content/LeadSquared/Common/img/user_option_logout.png',
    RelatedConnectorId: null,
    CustomApplicationMenuId: null,
    Group: 2,
    Children: [],
    Path: 'signout',
    SortOrder: 4
  },
  {
    Id: '303',
    ParentId: null,
    Caption: 'Manage Users',
    HelpText: '',
    ShowHelptext: true,
    ControllerName: 'Settings',
    ActionName: 'ManageUsers',
    ImageURL: '/Content/LeadSquared/Common/img/user_option_manageusers.png',
    RelatedConnectorId: null,
    CustomApplicationMenuId: null,
    Group: 2,
    Children: [],
    Path: 'manageusers',
    SortOrder: 3
  },
  {
    Id: '600',
    ParentId: null,
    Caption: 'Help',
    HelpText: '',
    ShowHelptext: true,
    ControllerName: 'Help',
    ActionName: '',
    ImageURL: null,
    RelatedConnectorId: null,
    CustomApplicationMenuId: null,
    Group: 7,
    Children: [
      {
        Id: '602',
        ParentId: '600',
        Caption: 'Help Center',
        HelpText: '',
        ShowHelptext: true,
        ControllerName: '',
        ActionName: 'https://help.leadsquared.com',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 7,
        Children: [],
        Path: 'help>>helpcenter',
        SortOrder: 200
      },
      {
        Id: '603',
        ParentId: '600',
        Caption: 'Product Updates',
        HelpText: '',
        ShowHelptext: true,
        ControllerName: '',
        ActionName: 'https://help.leadsquared.com/news',
        ImageURL: null,
        RelatedConnectorId: null,
        CustomApplicationMenuId: null,
        Group: 7,
        Children: [],
        Path: 'help>>productupdates',
        SortOrder: 300
      }
    ],
    Path: 'help',
    SortOrder: 0
  }
];
