import { StorageKey, getItem } from 'common/utils/storage-manager';

export const ACTIVITY = {
  LEAD_ASSIGNED: 3001,
  STAGE_CHANGE: 3002,
  LEAD_MERGED: 3003,
  SOURCE_CHANGE: 3004,
  LEAD_ASSOCIATED: 3006,
  OPPORTUNITY_ASSIGNED: 20000,
  OPPORTUNITY_STATUS_CHANGE: 20001,
  OPPORTUNITY_STATUS_CHANGE1: 20006,
  OPPORTUNITY_SOURCE_CHANGE: 20002,
  DELETE_LOG: 19001,
  OPPORTUNITY_DELETE_LOG: 19002,
  ON_OPPORTUNITY_DELETE_LOG: 19003,
  TASK: 3010,
  NOTES: 3009,
  LOGGED_OUT_PORTAL: 96,
  LOGGED_INTO_PORTAL: 93,
  FORGOT_PASSWORD: 95,
  CHANGED_PASSWORD_OF_PORTAL: 94,
  PUBLISHER_TRACKING: 11001,
  REGISTER_ON_PORTAL: 91,
  CHANGE_LOG: 3011,
  OPPORTUNITY_CHANGE_LOG: 20005,
  CONVERTED_TO_LEAD: 19,
  PAGE_VISITED_ON_WEBSITE: 2,
  FORM_SUBMITTED_ON_WEBSITE: 3,
  TRACKING_URL_CLICKED: 4,
  CONVERSION_BUTTON_CLICKED: 20,
  EMAIL_BOUNCED: 10,
  EMAIL_SENT: 2001,
  EMAIL_OPENED: 'Email Opened',
  EMAIL_LINK_CLICKED: 1,
  EMAIL_RESUBSCRIBE: 15,
  EMAIL_UNSUBSCRIBE: 5,
  EMAIL_POSITIVE_RESPONSE: 12,
  EMAIL_NEGATIVE_RESPONSE: 13,
  EMAIL_NEUTRAL_RESPONSE: 14,
  EMAIL_INBOUND_LEAD: 18,
  DATA_PROTECTION_REQUEST: 27,
  PRIVACY_COOKIE_CONSENT: 24,
  MAILING_PREFERENCE_LINK_CLICKED: 8,
  SUBSCRIBE_TO_NEWSLETTER: 42,
  UNSUBSCRIBE_TO_NEWSLETTER: 62,
  VIEW_IN_BROWSER_LINK_CLICKED: 11,
  EMAIL_MARKED_AS_SPAM: 9,
  EMAIL_UNSUBSCRIBE_LINK_CLICKED: 6,
  INBOUND_PHONE_CALL_ACTIVITY: 21,
  OUTBOUND_PHONE_CALL_ACTIVITY: 22,
  PAYMENT: 98,
  DYNAMIC_FORM_SUBMISSION: 97,
  OPTED_IN_FOR_EMAIL: 25,
  OPTED_OUT_FOR_EMAIL: 26,
  DO_NOT_TRACK_REQUEST: 28,
  SALES: 30,
  LEAD_CAPTURE: 23,
  DUPLICATE_OPP_DETECTED: 32,
  OPPORTUNITY_CAPTURE: 33,
  OPPORTUNITY_NOTES: 20003,
  TOP_BAR_VIEWED: 151,
  TOP_BAR_CTA_BUTTON_CLICKED: 152,
  CUSTOM_EMAIL: 'CustomEmail',
  FORM_SAVED_AS_DRAFT_ON_PORTAL: 21500
};

export const ACTIVITY_TYPE = {
  EMAIL_SENT: 25,
  WEB_ACTIVITY: 1,
  PHONE_ACTIVITY: 3,
  GDPR_ACTIVITY: 6,
  PORTAL_ACTIVITY: 7,
  DYNAMIC_FORM: 8,
  CUSTOM_ACTIVITY: 2
};

export const EMAIL_BOUNCED_TYPES = {
  EMAIL_BOUNCED_WHILE_DELIVERING_ZERO: '0',
  EMAIL_BOUNCED_WHILE_DELIVERING_SIX: '6',
  EMAIL_BOUNCED_WHILE_DELIVERING_TWELVE: '12'
};

export const EMAIL_SENT_TYPES = {
  SENT_WITH_SUBJECT: '0',
  SENT_NOTIFICATION_EMAIL: '3',
  SENT_WITH_SUBJECT_USER_EMAIL: '4',
  SENT_WITH_SUBJECT_EMAIL: '6',
  SENT_AUTOMATION_EMAIL: '12',
  SENT_EMAIL_SUBJECT_EIGHT: '8',
  SENT_EMAIL_THROUGH_EMAIL_CLIENT: '1',
  SENT_REFERRAL_CAMPAIGN_EMAIL: '7'
};

export const MAILING_PREFERENCE = {
  AUTOMATION_EMAIL_LINK_CLICKED: '12',
  EMAIL_LINK_CLICKED: '4'
};

export const NEWSLETTER_TYPES = {
  AUTOMATION_EMAIL: '12',
  EMAIL: '4'
};

export const VIEW_IN_BROWSER_LINK_CLICKED_TYPES = {
  EMAIL_WITH_CAMPAIGN_NAME: '0',
  EMAIL_WITHOUT_CAMPAIGN_NAME_ONE: '1',
  EMAIL_WITHOUT_CAMPAIGN_NAME_FOUR: '4',
  EMAIL_WITHOUT_CAMPAIGN_NAME_SIX: '6',
  EMAIL_WITHOUT_CAMPAIGN_NAME_SEVEN: '7',
  EMAIL_WITHOUT_CAMPAIGN_NAME_THREE: '3',
  EMAIL_WITHOUT_CAMPAIGN_NAME_TWELVE: '12'
};

export const EMAIL_CLICK = {
  OPENED_EMAIL_CAMPAIGN: '0',
  OPENED_EMAIL_SENT_BY_ONE: '1',
  OPENED_EMAIL_SENT_BY_FOUR: '4',
  OPENED_EMAIL_SENT_BY_EIGHT: '8',
  OPENED_EMAIL_SENT_BY_SIX: '6',
  OPENED_NOTIFICATION_EMAIL: '3',
  OPENED_REFERRAL_EMAIL: '7',
  OPENED_AUTOMATION_EMAIL: '12'
};

export const EMAIL_OPENED = {
  OPENED_EMAIL_CAMPAIGN: '0',
  OPENED_EMAIL_SENT_BY_ONE: '1',
  OPENED_EMAIL_SENT_BY_FOUR: '4',
  OPENED_EMAIL_SENT_BY_EIGHT: '8',
  OPENED_EMAIL_SENT_BY_SIX: '6',
  OPENED_NOTIFICATION_EMAIL: '3',
  OPENED_REFERRAL_EMAIL: '7',
  OPENED_AUTOMATION_EMAIL: '12'
};

export const EMAIL_UNSUBSCRIBE_TYPES = {
  EMAIL_CAMPAIGN: '0',
  EMAIL_SENT_BY_ONE: '1',
  EMAIL_SENT_BY_FOUR: '4',
  EMAIL_SENT_BY_SIX: '6',
  NOTIFICATION_EMAIL: '3',
  REFERRAL_EMAIL: '7',
  AUTOMATION_EMAIL: '12'
};

export const LEAD_AUDIT_EVENT_CODES = [
  ACTIVITY.LEAD_ASSIGNED,
  ACTIVITY.STAGE_CHANGE,
  ACTIVITY.LEAD_MERGED,
  ACTIVITY.SOURCE_CHANGE,
  ACTIVITY.LEAD_ASSOCIATED
];

export const OPP_AUDIT_EVENT_CODES = [
  ACTIVITY.OPPORTUNITY_ASSIGNED,
  ACTIVITY.OPPORTUNITY_STATUS_CHANGE,
  ACTIVITY.OPPORTUNITY_SOURCE_CHANGE,
  ACTIVITY.OPPORTUNITY_STATUS_CHANGE1
];

export const DELETE_AUDIT_EVENT_CODES = [
  ACTIVITY.DELETE_LOG,
  ACTIVITY.OPPORTUNITY_DELETE_LOG,
  ACTIVITY.ON_OPPORTUNITY_DELETE_LOG
];

export const PHONE_ACTIVITIES_TYPES = {
  ANSWERED: 'answered',
  COMPLETE: 'complete',
  NOT_ANSWERED: 'notanswered',
  MISSED: 'missed',
  INCOMPLETE: 'incomplete',
  VOICEMAIL: 'voicemail',
  REJECTED: 'rejected',
  CALL_FAILURE: 'callfailure'
};

export const DEFAULT_PAGE_SIZE: number = getItem(StorageKey.AhDefaultPageSize) || 25;

export const ALL_TIME = 'all_time';

export const OPPORTUNITY = 'Opportunity';

export const PERMISSION_ERROR_MSG =
  'You do not have sufficient permissions to perform operations on closed Opportunity. Please contact your Administrator';

// When custom AH tab is added through Manage Tabs and all activities are selected, activity codes contain selectAll
export const SELECT_ALL = 'selectAll';
// When custom AH tab is added through LDVC and all activities are selected, activity codes contain multiselect-all
export const MULTI_SELECT_ALL = 'multiselect-all';

export const activityType = {
  DataProtection: 'Data Protection Request',
  LEAD_SHARE_HISTORY: 30
};
